services:
  - type: web
    name: redactor-sidn
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: api_key
        sync: false
