services:
  - type: web
    name: redactor-sidn
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: waitress-serve --port=$PORT app:app
    envVars:
      - key: api_key
        sync: false
